before_build:
  - cd uploader
  - nuget restore

after_build:
  - "C:/Program Files (x86)/Inno Setup 6/ISCC.exe" inno_setup.iss

platform:
  - Any CPU

configuration:
  - Release

artifacts:
  - path: uploader/uploader/build/rel
    name: release_anycpu
  - path: output
    name: setup_anycpu